version: "3.11"

services:

  paint_mall_service:
    image: paint_mall_service:0.1
    container_name: paint_mall_service_api
    hostname: paint_mall_service
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
