repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #       args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length=79"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=79", "--ignore=E501 W503"]
  # - repo: https://github.com/pre-commit/pre-commit
  #   rev: "v3.2.1"
  #   hooks:
  #     - id: pylint
  #       args: ["-sn", "--disable=W0511"]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.1.1
  #   hooks:
  #     - id: mypy
  #       # args: []
  #       additional_dependencies:
  #         [
  #           anyio==3.6.2,
  #           click==8.1.3,
  #           h11==0.14.0,
  #           idna==3.4,
  #           pydantic==1.10.7,
  #           sniffio==1.3.0,
  #           starlette==0.26.1,
  #           typing-extensions==4.5.0,
  #           fastapi==0.95.0,
  #           uvicorn==0.21.1,
  #         ]
default_language_version:
  python: python3.11.1
