repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile black]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=79]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=79, --ignore=E501 W503]
  # - repo: https://github.com/pycqa/pylint
  #   rev: "v2.16.0"
  #   hooks:
  #     - id: pylint
  #       args: ["-sn", "--rcfile=pyproject.toml", --disable=W0511]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.0.0
  #   hooks:
  #     - id: mypy
  #       args: []
  #       additional_dependencies:
  #         [
  #           anyio==3.6.2,
  #           certifi==2022.12.7,
  #           click==8.1.3,
  #           fastapi==0.91.0,
  #           h11==0.14.0,
  #           httptools==0.5.0,
  #           idna==3.4,
  #           pydantic==1.10.4,
  #           python-dotenv==0.21.1,
  #           pyyaml==6.0,
  #           setuptools==67.2.0,
  #           sniffio==1.3.0,
  #           starlette==0.24.0,
  #           typing-extensions==4.4.0,
  #           urllib3==1.26.14,
  #           utm==0.7.0,
  #           uvicorn==0.20.0,
  #           uvloop==0.17.0,
  #           watchfiles==0.18.1,
  #           websockets==10.4,
  #         ]
default_language_version:
  python: python3.11.1
